export const productsMocks = [
  {
    id: '1',
    title: 'Опора тавровая хомутовая ТХ',
    type: 'Опорные конструкции',
    price: '849.9',
    gost: 'ГОСТ 14911-82',
    image: 'product-image-1.png',
    hit: true,
    discount: true,
    promotion: true,
  },
  {
    id: '2',
    title: 'Опора корпусная приварная КП',
    type: 'Детали крепления',
    price: '700',
    gost: 'ОСТ 36-146-88',
    image: 'product-image-1.png',
  },
  {
    id: '3',
    title: 'Опора корпусная хомутовая КХ',
    type: 'Узлы трубопроводов',
    price: '650',
    gost: 'ГОСТ 14911-82',
    image: 'product-image-1.png',
  },
  {
    id: '4',
    title: 'Опора подвижная ОПБ2',
    type: 'Детали крепления',
    price: '500',
    gost: 'НТС 65-06',
    image: 'product-image-1.png',
  },
];